import { readUserSnapshot, writeUserSnapshot, type UserSnapshot } from "./user-snapshot";
import { STRATEGY_REGISTRY, createQuantTask, nextRun, runBacktest, type PricePoint, type QuantAuditEntry, type QuantSchedule, type QuantSignal, type QuantTask } from "./quant-research";

type QuantSnapshot = UserSnapshot & {quantTasks?:QuantTask[];quantStrategies?:Array<{id:string;name:string;definitionId:string;parameters:Record<string,unknown>;createdAt:string}>;quantSchedules?:QuantSchedule[];quantSignals?:QuantSignal[];quantAudit?:QuantAuditEntry[];quantPaperPortfolios?:Array<Record<string,unknown>>};
const arrays=(snapshot:UserSnapshot):QuantSnapshot=>({...snapshot,quantTasks:Array.isArray(snapshot.quantTasks)?snapshot.quantTasks as QuantTask[]:[],quantStrategies:Array.isArray(snapshot.quantStrategies)?snapshot.quantStrategies as QuantSnapshot["quantStrategies"]:[],quantSchedules:Array.isArray(snapshot.quantSchedules)?snapshot.quantSchedules as QuantSchedule[]:[],quantSignals:Array.isArray(snapshot.quantSignals)?snapshot.quantSignals as QuantSignal[]:[],quantAudit:Array.isArray(snapshot.quantAudit)?snapshot.quantAudit as QuantAuditEntry[]:[],quantPaperPortfolios:Array.isArray(snapshot.quantPaperPortfolios)?snapshot.quantPaperPortfolios as Array<Record<string,unknown>>:[]});
async function state(){const saved=await readUserSnapshot();if(saved.status==="unauthorized")throw new Error("请先登录");return arrays(saved.status==="ready"?saved.snapshot:{});}
const audit=(action:string,targetId:string,status:string,details?:Record<string,unknown>):QuantAuditEntry=>({id:`qa-${crypto.randomUUID()}`,action,targetId,status,source:"anxin_quant_workspace",createdAt:new Date().toISOString(),details});

export async function listQuantState(){const snapshot=await state();return {tasks:snapshot.quantTasks,strategies:snapshot.quantStrategies,schedules:snapshot.quantSchedules,signals:snapshot.quantSignals,audit:snapshot.quantAudit,registry:STRATEGY_REGISTRY,data_status:"用户配置已从云端个人空间读取"};}
export async function saveNewQuantTask(goal:string){const snapshot=await state();const task=createQuantTask(goal);snapshot.quantTasks=[task,...(snapshot.quantTasks??[])].slice(0,100);snapshot.quantAudit=[audit("create_task",task.id,"awaiting_confirmation",{goal}),...(snapshot.quantAudit??[])].slice(0,300);await writeUserSnapshot(snapshot);return task;}
export async function getQuantTask(id:string){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===id);if(!task)throw new Error("未找到量化任务");return task;}
export async function updateQuantTask(id:string,action:"confirm"|"cancel"|"retry") {const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===id);if(!task)throw new Error("未找到量化任务");if(action==="confirm"){task.status="ready";task.confirmedAt=new Date().toISOString();}if(action==="cancel")task.status="cancelled";if(action==="retry"){task.status="ready";delete task.error;}task.updatedAt=new Date().toISOString();snapshot.quantAudit=[audit(action,task.id,task.status),...(snapshot.quantAudit??[])].slice(0,300);await writeUserSnapshot(snapshot);return task;}
export async function saveStrategy(input:{name?:string;definitionId?:string;parameters?:Record<string,unknown>}){const snapshot=await state();const definition=STRATEGY_REGISTRY.find(item=>item.id===input.definitionId);if(!definition)throw new Error("策略定义不存在");const saved={id:`qs-${crypto.randomUUID()}`,name:input.name?.trim()||definition.name,definitionId:definition.id,parameters:{...definition.parameters,...input.parameters},createdAt:new Date().toISOString()};snapshot.quantStrategies=[saved,...(snapshot.quantStrategies??[])].slice(0,100);snapshot.quantAudit=[audit("save_strategy",saved.id,"saved"),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return saved;}
export async function updateStrategy(id:string,input:Record<string,unknown>){const snapshot=await state();const found=snapshot.quantStrategies?.find(item=>item.id===id);if(!found)throw new Error("未找到策略");if(typeof input.name==="string"&&input.name.trim())found.name=input.name.trim();if(input.parameters&&typeof input.parameters==="object")found.parameters={...found.parameters,...input.parameters as Record<string,unknown>};snapshot.quantAudit=[audit("update_strategy",id,"saved"),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return found;}
export async function deleteStrategy(id:string){const snapshot=await state();snapshot.quantStrategies=(snapshot.quantStrategies??[]).filter(item=>item.id!==id);snapshot.quantAudit=[audit("delete_strategy",id,"deleted"),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return {status:"deleted",id};}
export async function backtestTask(input:{taskId?:string;prices?:PricePoint[];costBps?:number}){const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===input.taskId);if(input.taskId&&!task)throw new Error("未找到量化任务");if(task&&!task.confirmedAt)throw new Error("运行历史模拟前必须确认任务配置");const result=runBacktest(input.prices??[],input.costBps);snapshot.quantAudit=[audit("run_backtest",input.taskId??"ad_hoc",result.status,{dataStatus:result.dataStatus,points:input.prices?.length??0}),...(snapshot.quantAudit??[])];if(task){task.status=result.status==="ready"?"completed":"failed";task.error=result.status==="missing_data"?result.dataStatus:undefined;task.updatedAt=new Date().toISOString();task.plan=task.plan.map(item=>item.tool==="run_quant_backtest"?{...item,status:result.status==="ready"?"completed":"failed"}:item);}await writeUserSnapshot(snapshot);return result;}
export async function savePaperRun(input:{taskId?:string;name?:string;positions?:unknown[];confirmed?:boolean}){if(input.confirmed!==true)throw new Error("创建模拟组合前必须明确确认");const snapshot=await state();const paper={id:`paper-${crypto.randomUUID()}`,taskId:input.taskId??null,name:input.name?.trim()||"模拟组合",positions:Array.isArray(input.positions)?input.positions:[],accountType:"paper",connectedToBroker:false,createdAt:new Date().toISOString()};snapshot.quantPaperPortfolios=[paper,...(snapshot.quantPaperPortfolios??[])].slice(0,50);snapshot.quantAudit=[audit("create_paper_portfolio",paper.id,"saved"),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return paper;}
export async function createSchedule(input:{taskId?:string;name?:string;frequency?:QuantSchedule["frequency"];confirmed?:boolean}){if(input.confirmed!==true)throw new Error("创建计划前必须明确确认");const snapshot=await state();const task=snapshot.quantTasks?.find(item=>item.id===input.taskId);if(!task)throw new Error("未找到量化任务");const frequency=input.frequency??task.extraction.frequency;const schedule:QuantSchedule={id:`schedule-${crypto.randomUUID()}`,taskId:task.id,name:input.name?.trim()||`${task.goal.slice(0,20)} · 定期研究`,frequency,status:"active",nextRunAt:nextRun(frequency),runnerStatus:"unavailable",createdAt:new Date().toISOString()};snapshot.quantSchedules=[schedule,...(snapshot.quantSchedules??[])].slice(0,100);snapshot.quantAudit=[audit("create_schedule",schedule.id,"configured",{runnerStatus:"unavailable"}),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return schedule;}
export async function changeSchedule(id:string,action:"pause"|"resume"|"delete"){const snapshot=await state();const found=snapshot.quantSchedules?.find(item=>item.id===id);if(!found)throw new Error("未找到计划");if(action==="delete")snapshot.quantSchedules=(snapshot.quantSchedules??[]).filter(item=>item.id!==id);else found.status=action==="pause"?"paused":"active";snapshot.quantAudit=[audit(`${action}_schedule`,id,action),...(snapshot.quantAudit??[])];await writeUserSnapshot(snapshot);return action==="delete"?{status:"deleted",id}:found;}
