import {authenticatedOwnerKey,getUserDatabase} from "./user-snapshot";

type StudyInput={reviewId:string;testerCode:string;result:"已修改"|"维持计划"|"已延迟";durationSeconds?:number;satisfaction:number;riskUnderstood:boolean;repeatIntent:boolean;paidIntent:boolean};

async function ensureTable(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS user_study_events (
  owner_key TEXT NOT NULL, review_key TEXT NOT NULL, participant_key TEXT NOT NULL,
  result TEXT NOT NULL, duration_seconds INTEGER, satisfaction INTEGER NOT NULL,
  risk_understood INTEGER NOT NULL, repeat_intent INTEGER NOT NULL, paid_intent INTEGER NOT NULL,
  created_at TEXT NOT NULL, PRIMARY KEY(owner_key,review_key)
)`).run();}
async function digest(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(item=>item.toString(16).padStart(2,"0")).join("");}

export async function saveUserStudyEvent(input:StudyInput){const owner=await authenticatedOwnerKey();if(!owner)throw new Error("请先登录");const db=await getUserDatabase();await ensureTable(db);const reviewKey=await digest(`${owner}:${input.reviewId}`);const participantKey=await digest(`${owner}:${input.testerCode.trim().toUpperCase()}`);await db.prepare(`INSERT INTO user_study_events(owner_key,review_key,participant_key,result,duration_seconds,satisfaction,risk_understood,repeat_intent,paid_intent,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_key,review_key) DO UPDATE SET participant_key=excluded.participant_key,result=excluded.result,duration_seconds=excluded.duration_seconds,satisfaction=excluded.satisfaction,risk_understood=excluded.risk_understood,repeat_intent=excluded.repeat_intent,paid_intent=excluded.paid_intent,created_at=excluded.created_at`).bind(owner,reviewKey,participantKey,input.result,Number.isFinite(input.durationSeconds)?Math.max(0,Math.round(input.durationSeconds!)):null,Math.min(5,Math.max(1,Math.round(input.satisfaction))),input.riskUnderstood?1:0,input.repeatIntent?1:0,input.paidIntent?1:0,new Date().toISOString()).run();return{status:"saved" as const};}

export async function readUserStudySummary(){const db=await getUserDatabase();await ensureTable(db);const response=await db.prepare(`SELECT COUNT(*) reviews,COUNT(DISTINCT participant_key) participants,SUM(CASE WHEN result!='维持计划' THEN 1 ELSE 0 END) changed,SUM(risk_understood) understood,SUM(repeat_intent) repeat_intent,SUM(paid_intent) paid_intent,AVG(duration_seconds) average_seconds,AVG(satisfaction) average_satisfaction FROM user_study_events`).all() as {results?:Array<Record<string,number|null>>};const row=response.results?.[0]??{};return{reviews:Number(row.reviews??0),participants:Number(row.participants??0),changed:Number(row.changed??0),understood:Number(row.understood??0),repeatIntent:Number(row.repeat_intent??0),paidIntent:Number(row.paid_intent??0),averageSeconds:row.average_seconds==null?null:Math.round(Number(row.average_seconds)),averageSatisfaction:row.average_satisfaction==null?null:Number(Number(row.average_satisfaction).toFixed(1))};}

export async function exportCurrentUserStudyCsv(){const owner=await authenticatedOwnerKey();if(!owner)throw new Error("请先登录");const db=await getUserDatabase();await ensureTable(db);const response=await db.prepare(`SELECT substr(participant_key,1,12) participant,result,duration_seconds,satisfaction,risk_understood,repeat_intent,paid_intent,created_at FROM user_study_events WHERE owner_key=? ORDER BY created_at DESC`).bind(owner).all() as {results?:Array<Record<string,unknown>>};const header=["匿名参与者","最终选择","完成耗时秒","满意度","看懂风险","再次使用","付费测试","提交时间"];const rows=(response.results??[]).map(row=>[row.participant,row.result,row.duration_seconds,row.satisfaction,row.risk_understood,row.repeat_intent,row.paid_intent,row.created_at]);const escape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;return `\uFEFF${[header,...rows].map(row=>row.map(escape).join(",")).join("\n")}`;}
