"use client";

import {useEffect,useMemo,useState} from "react";
import {Activity,ArrowRight,CalendarClock,Check,ChevronRight,Database,FileClock,FlaskConical,Layers3,Pause,Play,ShieldCheck,Sparkles,TriangleAlert} from "lucide-react";
import {STRATEGY_REGISTRY,type BacktestResult,type PricePoint,type QuantSchedule,type QuantTask} from "@/app/lib/quant-research";

type QuantState={tasks:QuantTask[];schedules:QuantSchedule[];audit:Array<{id:string;action:string;status:string;createdAt:string}>};
const frequencyLabel:Record<string,string>={manual:"手动运行",event:"事件触发",hourly:"每小时",daily_close:"每日收盘后",weekly:"每周",monthly:"每月"};
const moduleLabel:Record<string,string>={strategy_overview:"策略概览",strategy_config:"规则配置",backtest:"历史模拟",paper_portfolio:"模拟组合",news:"新闻观察",social_sentiment:"社交情绪",fundamental_validation:"基本面核验",portfolio_impact:"持仓影响",risk_metrics:"风险指标",signal_history:"信号历史",strategy_comparison:"策略比较",sensitivity:"参数敏感性",schedule:"研究计划",ai_report:"AI 研究报告",execution_log:"执行记录"};
const examples=["每天收盘后分析我的 ETF 持仓，检查重复暴露和最大回撤","每周观察科技板块风险，结合新闻与基本面，不生成买卖指令","用 20 日和 60 日均线研究 510300，加入交易成本和参数敏感性","每月模拟再平衡一次，比较真实持仓与模拟组合的风险差异"];

function taskStatus(task?:QuantTask){if(!task)return {label:"尚未创建",tone:"quiet"};return task.status==="awaiting_confirmation"?{label:"等待确认",tone:"pending"}:task.status==="completed"?{label:"已完成",tone:"ready"}:task.status==="failed"?{label:"需要数据",tone:"warning"}:task.status==="cancelled"?{label:"已取消",tone:"quiet"}:{label:"配置已确认",tone:"ready"};}

export function QuantWorkspace(){
  const [goal,setGoal]=useState(examples[0]);const [state,setState]=useState<QuantState>({tasks:[],schedules:[],audit:[]});const [task,setTask]=useState<QuantTask>();const [busy,setBusy]=useState("");const [message,setMessage]=useState("");const [priceText,setPriceText]=useState("");const [backtest,setBacktest]=useState<BacktestResult>();const [view,setView]=useState<"build"|"validate"|"schedule"|"audit">("build");
  const load=async()=>{const response=await fetch("/quant/tasks",{cache:"no-store"});if(!response.ok)return;const data=await response.json() as QuantState;setState(data);if(!task&&data.tasks?.[0])setTask(data.tasks[0]);};
  useEffect(()=>{let active=true;fetch("/quant/tasks",{cache:"no-store"}).then(response=>response.ok?response.json():null).then((data:QuantState|null)=>{if(!active||!data)return;setState(data);if(data.tasks?.[0])setTask(data.tasks[0]);}).catch(()=>{});return()=>{active=false};},[]);
  const selectedStrategies=useMemo(()=>task?.extraction.strategyIds.map(id=>STRATEGY_REGISTRY.find(item=>item.id===id)).filter(Boolean)??[],[task]);const status=taskStatus(task);
  const create=async()=>{setBusy("create");setMessage("");setBacktest(undefined);try{const response=await fetch("/quant/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({goal})});const data=await response.json() as {task?:QuantTask;message?:string};if(!response.ok||!data.task)throw new Error(data.message||"无法生成配置");setTask(data.task);setView("build");await load();}catch(error){setMessage(error instanceof Error?error.message:"无法生成配置");}finally{setBusy("");}};
  const act=async(action:"confirm"|"cancel"|"retry")=>{if(!task)return;setBusy(action);setMessage("");try{const response=await fetch(`/quant/tasks/${task.id}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({confirmed:true})});const data=await response.json() as {task?:QuantTask;message?:string};if(!response.ok||!data.task)throw new Error(data.message||"操作失败");setTask(data.task);await load();if(action==="confirm")setView("validate");}catch(error){setMessage(error instanceof Error?error.message:"操作失败");}finally{setBusy("");}};
  const parsePrices=():PricePoint[]=>priceText.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [date,close]=line.split(/[,，\t]/);return {date:date?.trim(),close:Number(close)}}).filter(item=>item.date&&Number.isFinite(item.close));
  const run=async()=>{if(!task)return;setBusy("run");setMessage("");try{const response=await fetch("/quant/backtest",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.id,prices:parsePrices(),costBps:13})});const data=await response.json() as {result?:BacktestResult;message?:string};if(!response.ok||!data.result)throw new Error(data.message||"运行失败");setBacktest(data.result);await load();}catch(error){setMessage(error instanceof Error?error.message:"运行失败");}finally{setBusy("");}};
  const schedule=async()=>{if(!task)return;setBusy("schedule");setMessage("");try{const response=await fetch("/quant/schedule",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.id,frequency:task.extraction.frequency,confirmed:true})});const data=await response.json() as {message?:string};if(!response.ok)throw new Error(data.message||"创建失败");await load();setMessage("研究计划已保存。当前托管环境尚未接入定时运行器，系统不会假装已经自动执行。");}catch(error){setMessage(error instanceof Error?error.message:"创建失败");}finally{setBusy("");}};
  const changeSchedule=async(item:QuantSchedule)=>{await fetch(`/quant/schedules/${item.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({action:item.status==="active"?"pause":"resume"})});await load();};
  return <section className="quant-lab">
    <header className="quant-command"><div><span>研究任务</span><h2>描述目标，先生成可检查的研究配置</h2><p>Agent 只组合已登记的数据与分析工具。规则、数据范围和计划在确认前不会运行或保存。</p></div><div className="quant-command-box"><textarea value={goal} onChange={event=>setGoal(event.target.value)} maxLength={600} aria-label="量化研究目标"/><button onClick={()=>void create()} disabled={!goal.trim()||busy==="create"}>{busy==="create"?"正在整理…":"生成研究配置"}<ArrowRight/></button></div><div className="quant-examples">{examples.map(item=><button key={item} onClick={()=>setGoal(item)}>{item}</button>)}</div></header>
    <div className="quant-context-bar"><div><i className={status.tone}/><span>当前任务</span><b>{task?.goal??"输入目标后开始"}</b></div><div><span>状态</span><strong>{status.label}</strong></div><div><span>数据</span><strong>{task?task.extraction.dataRequirements.join(" · "):"尚未请求"}</strong></div><div><span>频率</span><strong>{task?frequencyLabel[task.extraction.frequency]:"—"}</strong></div></div>
    <nav className="quant-workflow-nav" aria-label="量化研究步骤">{[["build","1 配置"],["validate","2 核验"],["schedule","3 计划"],["audit","4 记录"]].map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id as typeof view)}>{label}</button>)}</nav>
    {message&&<div className="quant-inline-message"><TriangleAlert/><span>{message}</span></div>}
    {view==="build"&&<div className="quant-config-grid">
      <section className="quant-panel quant-plan"><header><div><span>Agent 执行计划</span><h3>{task?"配置预览":"等待研究目标"}</h3></div><em>{task?.workspacePatch.requiresConfirmation?"需确认":"—"}</em></header>{task?<div className="quant-plan-steps">{task.plan.map((step,index)=><article key={step.id}><i>{step.status==="completed"?<Check/>:index+1}</i><span><b>{step.title}</b><small>{step.tool} · {step.requiresConfirmation?"确认后运行":"读取不需确认"}</small></span></article>)}</div>:<Empty icon={<Sparkles/>} title="这里会显示任务拆解" detail="包括数据读取、回测、风险检查和报告步骤。"/>}</section>
      <section className="quant-panel"><header><div><span>策略与边界</span><h3>模型理解了什么</h3></div></header>{task?<><div className="quant-strategy-list">{selectedStrategies.map(item=><article key={item!.id}><div><b>{item!.name}</b><small>{item!.description}</small></div><span>{item!.category}</span></article>)}</div><dl className="quant-definition-list"><div><dt>资产范围</dt><dd>{task.extraction.assets.length?task.extraction.assets.join("、"):"尚未指定"}</dd></div><div><dt>运行频率</dt><dd>{frequencyLabel[task.extraction.frequency]}</dd></div><div><dt>风险检查</dt><dd>{task.extraction.analysisRequirements.join("、")}</dd></div></dl>{task.extraction.missingInformation.length>0&&<aside className="quant-missing"><CircleHelpIcon/><div><b>运行前仍需补充</b><p>{task.extraction.missingInformation.join("；")}</p></div></aside>}{task.extraction.warnings.map(item=><aside className="quant-warning" key={item}><TriangleAlert/><span>{item}</span></aside>)}</>:<Empty icon={<ShieldCheck/>} title="没有静默默认值" detail="系统会把未明确的资产范围和风险边界标出来。"/>}</section>
      <section className="quant-panel quant-modules"><header><div><span>工作台 Patch</span><h3>将显示的研究模块</h3></div></header>{task?<div>{task.extraction.modules.map((module,index)=><article key={module}><span>{String(index+1).padStart(2,"0")}</span><b>{moduleLabel[module]}</b><small>{index<2?"顶部":"主区域"}</small></article>)}</div>:<Empty icon={<Layers3/>} title="模块按目标组合" detail="新闻、社交、基本面和持仓影响只在需要时出现。"/>}</section>
      {task?.status==="awaiting_confirmation"&&<footer className="quant-confirm-bar"><div><b>确认后才会读取数据和运行研究</b><span>确认配置不代表认可策略，也不会连接真实交易账户。</span></div><button className="secondary" onClick={()=>void act("cancel")}>取消</button><button onClick={()=>void act("confirm")} disabled={!!busy}>确认配置<ChevronRight/></button></footer>}
    </div>}
    {view==="validate"&&<div className="quant-validate-layout"><section className="quant-panel quant-data-input"><header><div><span>数据入口</span><h3>粘贴真实日线数据</h3></div><Database/></header><p>每行格式为 <code>日期,收盘价</code>。系统不会自动填充演示价格，也不会把缺失数据写成结果。</p><textarea value={priceText} onChange={event=>setPriceText(event.target.value)} placeholder={"2026-01-05,4.12\n2026-01-06,4.18\n…至少 60 条有效日线"}/><div className="quant-input-footer"><span>已识别 {parsePrices().length} 条</span><button onClick={()=>void run()} disabled={!task?.confirmedAt||busy==="run"}>{busy==="run"?"正在核验…":"运行历史核验"}<FlaskConical/></button></div>{!task?.confirmedAt&&<small>先回到“配置”确认任务。</small>}</section><section className="quant-panel quant-result"><header><div><span>历史核验结果</span><h3>{backtest?.status==="ready"?"数据计算完成":"等待有效数据"}</h3></div><Activity/></header>{backtest?.metrics?<><div className="quant-metric-grid"><Metric label="区间收益" value={`${backtest.metrics.totalReturnPct}%`}/><Metric label="年化波动" value={`${backtest.metrics.volatilityPct}%`}/><Metric label="最大回撤" value={`${backtest.metrics.maxDrawdownPct}%`}/><Metric label="Sharpe" value={String(backtest.metrics.sharpe)}/></div><div className="quant-mini-series">{backtest.series.filter((_,index)=>index%Math.max(1,Math.floor(backtest.series.length/24))===0).map(item=><i key={item.date} style={{height:`${Math.max(8,Math.min(84,item.strategy/2))}%`}} title={`${item.date} ${item.strategy}`}/>)}</div><p>{backtest.warnings.join(" ")}</p></>:<Empty icon={<Database/>} title={backtest?.dataStatus??"没有数据，就没有绩效数字"} detail="请粘贴已授权来源的真实价格序列；后续数据连接器也必须返回来源和时间。"/>}<footer><span>{backtest?.source??"来源：尚未提供"}</span><small>{backtest?.disclaimer??"历史模拟只用于研究，不构成投资建议。"}</small></footer></section></div>}
    {view==="schedule"&&<div className="quant-schedule-layout"><section className="quant-panel"><header><div><span>计划预览</span><h3>{task?frequencyLabel[task.extraction.frequency]:"尚未配置"}</h3></div><CalendarClock/></header><div className="quant-schedule-map"><article><b>市场数据</b><span>{task?.extraction.dataRequirements.includes("daily_prices")?"收盘日线":"按数据源"}</span></article><ArrowRight/><article><b>规则计算</b><span>确定性引擎</span></article><ArrowRight/><article><b>研究报告</b><span>来源与时间保留</span></article></div><aside className="quant-warning"><TriangleAlert/><span>当前 Sites 环境未配置后台定时运行器。可保存计划和下次运行时间，但不会假装任务已自动执行。</span></aside><button onClick={()=>void schedule()} disabled={!task?.confirmedAt||busy==="schedule"}>确认并保存计划</button></section><section className="quant-panel"><header><div><span>已保存计划</span><h3>{state.schedules.length} 项</h3></div></header>{state.schedules.length?<div className="quant-saved-list">{state.schedules.map(item=><article key={item.id}><div><b>{item.name}</b><small>{frequencyLabel[item.frequency]} · 运行器{item.runnerStatus==="unavailable"?"未接入":"已配置"}</small></div><button onClick={()=>void changeSchedule(item)}>{item.status==="active"?<><Pause/>暂停</>:<><Play/>恢复</>}</button></article>)}</div>:<Empty icon={<CalendarClock/>} title="还没有研究计划" detail="计划必须由你确认，并可随时暂停或删除。"/>}</section></div>}
    {view==="audit"&&<section className="quant-panel quant-audit"><header><div><span>执行与审计</span><h3>每次修改都有记录</h3></div><FileClock/></header><div className="quant-audit-table"><div><span>时间</span><span>动作</span><span>状态</span></div>{state.audit.slice(0,20).map(item=><div key={item.id}><time>{new Date(item.createdAt).toLocaleString("zh-CN")}</time><b>{item.action}</b><span>{item.status}</span></div>)}</div>{!state.audit.length&&<Empty icon={<FileClock/>} title="暂无执行记录" detail="创建、确认、运行和计划变更会保存在这里。"/>}</section>}
  </section>;
}

function Empty({icon,title,detail}:{icon:React.ReactNode;title:string;detail:string}){return <div className="quant-empty-state">{icon}<b>{title}</b><span>{detail}</span></div>}
function Metric({label,value}:{label:string;value:string}){return <article><span>{label}</span><b>{value}</b></article>}
function CircleHelpIcon(){return <span className="quant-help">?</span>}
